name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Unit Tests + SonarQube
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for SonarQube scan

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      # Step 4: Run Unit Tests with Coverage
      - name: Run Unit Tests with Coverage
        run: |
          coverage run -m unittest discover -s src -p "test*.py"
          coverage xml

      # Step 5: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=RamkishoreK_devsecopsSonar
            -Dsonar.organization=ramkishorek
            -Dsonar.sources=src
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

              
      # Step 6: Create Docker Network
      - name: Create Docker Network
        run: docker network create zapnet

      # Step 7: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t adrenolad/myapp:latest .

      # Step 8: Run Docker Container (Expose Port 8888)
      - name: Run Docker Container
        run: |
          docker run -d \
            --network zapnet \
            -p 8888:8001 \
            --name adrenolad \
            adrenolad/myapp:latest
          sleep 10

      # Step 9: OWASP ZAP baseline scan
      - name: Run OWASP ZAP Scan
        run: |
          mkdir zap-output
          chmod 777 zap-output
          
          docker run --rm \
            --network zapnet \
            -v $(pwd)/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            /zap/zap-baseline.py \
            -t http://adrenolad:8001 \
            --autooff \
            -I \
            -x zap-report.xml \
            -r zap-report.html \
            -J zap-report.json \
            -w zap-warnings.md

      # Step 10: Upload ZAP report
      - uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/*

      # Step 11: Stop Container
      - name: Stop Container
        run: |
          docker stop adrenolad || true
          docker rm adrenolad || true

      # Step 12: Remove network
      - name: Remove Docker Network
        run: docker network rm zapnet || true
